### ISSUE TITLE
Security model bypass?

### ISSUE THREAD

**Issue by mothershipper** [contentful-labs/kube-secret-syncer#39]
Noticed that your security model docs say the following:

```
By default, kube-secret-syncer will use the Kubernetes node's IAM role to list and retrieve the secrets. 
However, when synced secrets have an IAMRole field defined, kube-secret-syncer will assume that role 
before retrieving the secret. This implies that the role specified by IAMRole can be assumed by the role
of the Kubernetes node kube-secret-syncer runs on.

To ensure a specific namespace only has access to the secrets it needs to, kube-secret-syncer will use 
the "iam.amazonaws.com/allowed-roles" annotation on the namespace (originally used by kube2iam) 
to validate that this role can be assumed for that namespace.
```

If this is the case, couldn't any container in the cluster use the node IAM role to fetch the secret directly regardless of namespace? Or am I missing something?

Might want to document how this could work with a service-account (IRSA) or annotations (kube2iam, kiam, etc.) when deploying the kube-secret-syncer to avoid the auth bypass scenario if it exists.

**Comment by yannh** [comment]
Hi @mothershipper , no you're very right, I believe we assumed that a solution such as kube2iam vs kiam would be used without properly documenting it. 

To go more in detail before we update the documentation:
 * To prevent the issue you are talking about, your cluster needs to run a solution such as kube2iam or kiam.
 * The nodes need to be running under a service account that allows them to assume any role that your containers might need to assume.
 * Kube-secret-syncer needs to run in its own namespace, a namespace that has the permission (aka kube2iam/kiam annotation set) to assume all the roles that might need to be assumed to pull secrets.
 * The namespace in which you are going to setup secret syncing & deploy SyncedSecrets will also need to have an annotation to explicitly whitelist what roles can be assumed.

For each namespace, you would eventually create a different IAM Role that can only pull a certain set of secrets.
Kube2iam/Kiam would prevent containers in your namespace from assuming a non-authorized role.

By default, kube-secret-syncer uses the kube2iam annotation to validate that the role to be assumed to pull the secret specified in the "SyncedSecret" resource is authorized for this namespace. For anything else - kube2iam/kiam are the ones securing your namespace. 

Does this answer your question?

**Comment by mothershipper** [comment]
Yup, this wasn't a question as much as a heads up on the docs :)

**Comment by yannh** [comment]
@mothershipper I updated the docs, instead of recommending the use of kube2iam/kiam, I actually removed the reference to the instance role, since you should be able to configure the auth using any authentication method supported by the AWS SDK. Is this any better?

**Comment by yannh** [comment]
I will close this now, hopefully it is more clear now.
