### ISSUE TITLE
Docs do not jive with project

### ISSUE THREAD

**Issue by alop** [contentful-labs/kube-secret-syncer#56]
Simply following the docs causes many errors.
Running `make docker-build kind`
The makefile assumes the context is "kubernetes-admin@kind" - but every new cluster I bring up is "kind-kind"
so running `KIND_CTX=kind-kind make docker-build kind` gives a couple of errors

Firstly,   ` @kubectl --context=${KIND_CTX} apply -f config/samples/kube-secret-syncer-ns.yaml ` This file has been renamed `k8s-secret-syncer-ns.yaml`

Secondly, the deployment sample has the container image field under EnvVars, which throws
```
error: error validating "STDIN": error validating data: ValidationError(Deployment.spec.template.spec.containers[0].env[0]): unknown field "image" in io.k8s.api.core.v1.EnvVar; if you choose to ignore these errors, turn validation off with --validate=false
```

**Comment by yannh** [comment]
Hi @alop , thanks a lot for the feedback! We renamed this project from k8s-secret-syncer due to trademark issues, apparently some bits were not rewired. Will look at this soon.

**Comment by yannh** [comment]
Patch incoming! You're right on setting KIND_CTX, on the following error - it was apparently a mistake I made when renaming the project, see https://github.com/contentful-labs/kube-secret-syncer/commit/f5a2699203379c23dd126ac6774f2c4c40e98878#diff-ce0d597a9e5f20a8fe61c3ba5e6185a6b90cfef2c00bb5b5ef3e97b15b79f480  :disappointed:

**Comment by yannh** [comment]
Fix merged, closing this!
